import React from 'react'

export const places = [
  { label: "Chennai, India", value: "Chennai" },
  { label: "Mumbai, India", value: "Mumbai" },
  { label: "Delhi, India", value: "Delhi" },
  { label: "Kolkata, India", value: "Kolkata" },
  { label: "Bangalore, India", value: "Bangalore" },
  { label: "Hyderabad, India", value: "Hyderabad" },
  { label: "New York, USA", value: "New York" },
  { label: "Los Angeles, USA", value: "Los Angeles" },
  { label: "Chicago, USA", value: "Chicago" },
  { label: "Houston, USA", value: "Houston" },
  { label: "Phoenix, USA", value: "Phoenix" },
  { label: "Philadelphia, USA", value: "Philadelphia" },
  { label: "San Antonio, USA", value: "San Antonio" },
  { label: "San Diego, USA", value: "San Diego" },
  { label: "Dallas, USA", value: "Dallas" },
  { label: "San Jose, USA", value: "San Jose" },
  { label: "Austin, USA", value: "Austin" },
  { label: "Jacksonville, USA", value: "Jacksonville" },
  { label: "San Francisco, USA", value: "San Francisco" },
  { label: "Columbus, USA", value: "Columbus" },
  { label: "Indianapolis, USA", value: "Indianapolis" },
  { label: "Fort Worth, USA", value: "Fort Worth" },
  { label: "Charlotte, USA", value: "Charlotte" },
  { label: "Seattle, USA", value: "Seattle" },
  { label: "Denver, USA", value: "Denver" },
  { label: "Washington, USA", value: "Washington" },
  { label: "Boston, USA", value: "Boston" },
  { label: "El Paso, USA", value: "El Paso" },
  { label: "Nashville, USA", value: "Nashville" },
  { label: "Detroit, USA", value: "Detroit" },
  { label: "Oklahoma City, USA", value: "Oklahoma City" },
  { label: "Portland, USA", value: "Portland" },
  { label: "Las Vegas, USA", value: "Las Vegas" },
  { label: "Memphis, USA", value: "Memphis" },
  { label: "Louisville, USA", value: "Louisville" },
  { label: "Baltimore, USA", value: "Baltimore" },
  { label: "Milwaukee, USA", value: "Milwaukee" },
  { label: "Albuquerque, USA", value: "Albuquerque" },
  { label: "Tucson, USA", value: "Tucson" },
  { label: "Fresno, USA", value: "Fresno" },
  { label: "Sacramento, USA", value: "Sacramento" },
  { label: "Kansas City, USA", value: "Kansas City" },
  { label: "Atlanta, USA", value: "Atlanta" },
  { label: "Miami, USA", value: "Miami" },
  { label: "Paris, France", value: "Paris" },
  { label: "Marseille, France", value: "Marseille" },
  { label: "Lyon, France", value: "Lyon" },
  { label: "Toulouse, France", value: "Toulouse" },
  { label: "Nice, France", value: "Nice" },
  { label: "Nantes, France", value: "Nantes" },
  { label: "Strasbourg, France", value: "Strasbourg" },
  { label: "Montpellier, France", value: "Montpellier" },
  { label: "Bordeaux, France", value: "Bordeaux" },
  { label: "Lille, France", value: "Lille" },
  { label: "Rennes, France", value: "Rennes" },
  { label: "Reims, France", value: "Reims" },
  { label: "Le Havre, France", value: "Le Havre" },
  { label: "Saint-Étienne, France", value: "Saint-Étienne" },
  { label: "Toulon, France", value: "Toulon" },
  { label: "Angers, France", value: "Angers" },
  { label: "Grenoble, France", value: "Grenoble" },
  { label: "Dijon, France", value: "Dijon" },
  { label: "Nîmes, France", value: "Nîmes" },
  { label: "Aix-en-Provence, France", value: "Aix-en-Provence" },
  { label: "Beijing, China", value: "Beijing" },
  { label: "Shanghai, China", value: "Shanghai" },
  { label: "Guangzhou, China", value: "Guangzhou" },
  { label: "Shenzhen, China", value: "Shenzhen" },
  { label: "Chengdu, China", value: "Chengdu" },
  { label: "Wuhan, China", value: "Wuhan" },
  { label: "Xi'an, China", value: "Xi'an" },
  { label: "Hangzhou, China", value: "Hangzhou" },
  { label: "Chongqing, China", value: "Chongqing" },
  { label: "Nanjing, China", value: "Nanjing" },
  { label: "Tianjin, China", value: "Tianjin" },
  { label: "Shenyang, China", value: "Shenyang" },
  { label: "Harbin, China", value: "Harbin" },
  { label: "Suzhou, China", value: "Suzhou" },
  { label: "Qingdao, China", value: "Qingdao" },
  { label: "Dalian, China", value: "Dalian" },
  { label: "Zhengzhou, China", value: "Zhengzhou" },
  { label: "Jinan, China", value: "Jinan" },
  { label: "Changsha, China", value: "Changsha" },
  { label: "Kunming, China", value: "Kunming" },
  { label: "Seoul, South Korea", value: "Seoul" },
  { label: "Busan, South Korea", value: "Busan" },
  { label: "Incheon, South Korea", value: "Incheon" },
  { label: "Daegu, South Korea", value: "Daegu" },
  { label: "Daejeon, South Korea", value: "Daejeon" },
  { label: "Gwangju, South Korea", value: "Gwangju" },
  { label: "Suwon, South Korea", value: "Suwon" },
  { label: "Ulsan, South Korea", value: "Ulsan" },
  { label: "Yongin, South Korea", value: "Yongin" },
  { label: "Goyang, South Korea", value: "Goyang" },
  { label: "Cheongju, South Korea", value: "Cheongju" },
  { label: "Changwon, South Korea", value: "Changwon" },
  { label: "Jeonju, South Korea", value: "Jeonju" },
  { label: "Cheonan, South Korea", value: "Cheonan" },
  { label: "Ansan, South Korea", value: "Ansan" },
  { label: "Jeju, South Korea", value: "Jeju" },
  { label: "Osaka, Japan", value: "Osaka" },
  { label: "Tokyo, Japan", value: "Tokyo" },
  { label: "Nagoya, Japan", value: "Nagoya" },
  { label: "Yokohama, Japan", value: "Yokohama" },
  { label: "Sapporo, Japan", value: "Sapporo" },
  { label: "Kobe, Japan", value: "Kobe" },
  { label: "Kyoto, Japan", value: "Kyoto" },
  { label: "Fukuoka, Japan", value: "Fukuoka" },
  { label: "Hiroshima, Japan", value: "Hiroshima" },
  { label: "Sendai, Japan", value: "Sendai" },
  { label: "Kitakyushu, Japan", value: "Kitakyushu" },
  { label: "Chiba, Japan", value: "Chiba" },
  { label: "Sakai, Japan", value: "Sakai" },
  { label: "Shizuoka, Japan", value: "Shizuoka" },
  { label: "Nerima, Japan", value: "Nerima" },
];
